create table public.component_types
(
    created_at        date         not null,
    updated_at        date,
    component_type_id bigint generated by default as identity
        primary key,
    created_by        varchar(255) not null,
    type_name         varchar(255) not null,
    updated_by        varchar(255)
);

alter table public.component_types
    owner to postgres;

create table public.component_fields
(
    field_index        integer      not null,
    is_required        boolean      not null,
    component_field_id bigint generated by default as identity
        primary key,
    component_type_id  bigint       not null
        constraint fkcq8nbqeenv5cuq00v7o5yb6ii
            references public.component_types,
    default_value      varchar(255),
    field_name         varchar(255) not null,
    field_type         varchar(255) not null
);

alter table public.component_fields
    owner to postgres;

create table public.components_repositories
(
    created_at              date         not null,
    updated_at              date,
    component_repository_id bigint generated by default as identity
        primary key,
    created_by              varchar(255) not null,
    repository_name         varchar(255) not null,
    repository_url          varchar(255) not null,
    updated_by              varchar(255)
);

alter table public.components_repositories
    owner to postgres;

create table public.customers
(
    customer_id   bigint generated by default as identity
        primary key,
    create_at     varchar(255) not null,
    customer_name varchar(255) not null,
    update_at     varchar(255)
);

alter table public.customers
    owner to postgres;

create table public.environment_types
(
    created_at          date         not null,
    updated_at          date,
    environment_type_id bigint generated by default as identity
        primary key,
    created_by          varchar(255) not null,
    type_name           varchar(255) not null,
    updated_by          varchar(255)
);

alter table public.environment_types
    owner to postgres;

create table public.permissions
(
    permission_id   bigint generated by default as identity
        primary key,
    permission_name varchar(255) not null
        unique
);

alter table public.permissions
    owner to postgres;

create table public.projects
(
    created_at          date         not null,
    end_date            date,
    start_date          date         not null,
    updated_at          date,
    customer_id         bigint       not null
        constraint fk4rpwuljjwr5rygq9gwx36q8cj
            references public.customers,
    project_id          bigint generated by default as identity
        primary key,
    created_by          varchar(255) not null,
    project_description varchar(255),
    project_name        varchar(255) not null,
    status              varchar(255) not null,
    updated_by          varchar(255)
);

alter table public.projects
    owner to postgres;

create table public.roles
(
    role_id   bigint generated by default as identity
        primary key,
    role_name varchar(255)
);

alter table public.roles
    owner to postgres;

create table public.roles_permissions
(
    permission_id bigint not null
        constraint fkbx9r9uw77p58gsq4mus0mec0o
            references public.permissions,
    role_id       bigint not null
        constraint fkqi9odri6c1o81vjox54eedwyh
            references public.roles,
    primary key (permission_id, role_id)
);

alter table public.roles_permissions
    owner to postgres;

create table public.server_types
(
    server_type_id bigint generated by default as identity
        primary key,
    type_name      varchar(255) not null
);

alter table public.server_types
    owner to postgres;

create table public.environments
(
    environment_id      bigint generated by default as identity
        primary key,
    environment_type_id bigint       not null
        unique
        constraint fkl466bevukg0ochay3nc7kdk47
            references public.environment_types,
    server_type_id      bigint       not null
        unique
        constraint fkswlq2uob8g58iaeiq350diw0w
            references public.server_types,
    environment_name    varchar(255) not null,
    environment_url     varchar(255) not null
);

alter table public.environments
    owner to postgres;

create table public.environment_ports
(
    port_number         integer not null,
    environment_id      bigint  not null
        unique
        constraint fk2phrs3645qcyeqodkstj4blvv
            references public.environments,
    environment_port_id bigint generated by default as identity
        primary key
);

alter table public.environment_ports
    owner to postgres;

create table public.technology_types
(
    technology_type_id bigint generated by default as identity
        primary key,
    type_name          varchar(255) not null
);

alter table public.technology_types
    owner to postgres;

create table public.technology_type_versions
(
    technology_type_id         bigint       not null
        unique
        constraint fkjv261ir7qg8getalnny8xv8u5
            references public.technology_types,
    technology_type_version_id bigint generated by default as identity
        primary key,
    version                    varchar(255) not null
);

alter table public.technology_type_versions
    owner to postgres;

create table public.components
(
    created_at                 date         not null,
    updated_at                 date,
    component_repository_id    bigint       not null
        unique
        constraint fkn4jeha2u5bwc81f48hoftl41t
            references public.components_repositories,
    component_type_id          bigint       not null
        unique
        constraint fk51j4a15w7but5ck8mdt7962lc
            references public.component_types,
    environment_id             bigint       not null
        unique
        constraint fkgjp7r4rqvixr5h870notxo5yu
            references public.environments,
    environment_port_id        bigint
        unique
        constraint fkd05xpmgtt0ex3rgv4h4tdv4m2
            references public.environment_ports,
    project_component_id       bigint generated by default as identity
        primary key,
    technology_type_version_id bigint       not null
        unique
        constraint fkbgx6g4ba2b8fmdp0wip7q99tn
            references public.technology_type_versions,
    created_by                 varchar(255) not null,
    updated_by                 varchar(255)
);

alter table public.components
    owner to postgres;

create table public.field_values
(
    component_field_id   bigint       not null
        constraint fkcmxulv1ng42hbawkrciby35ph
            references public.component_fields,
    field_value_id       bigint generated by default as identity
        primary key,
    project_component_id bigint       not null
        constraint fkq1gustyobx284g74mmxgrf73a
            references public.components,
    value                varchar(255) not null
);

alter table public.field_values
    owner to postgres;

create table public.project_components
(
    components_project_component_id bigint not null
        constraint fk8jtqlyr2vfx1wpjc6u4rmoes
            references public.components,
    project_entity_project_id       bigint not null
        constraint fkp5tv8tik6rtgnn91ovkvx9n36
            references public.projects
);

alter table public.project_components
    owner to postgres;

create table public.users
(
    account_no_expired    boolean,
    account_no_locked     boolean,
    credential_no_expired boolean,
    is_enable             boolean,
    created_at            timestamp(6),
    updated_at            timestamp(6),
    user_id               bigint       not null
        primary key,
    email                 varchar(255) not null,
    lastname              varchar(255) not null,
    name                  varchar(255) not null,
    password              varchar(255)
);

alter table public.users
    owner to postgres;

create table public.user_role
(
    role_id bigint not null
        constraint fkt7e7djp752sqn6w22i6ocqy6q
            references public.roles,
    user_id bigint not null
        constraint fkj345gk1bovqvfame88rcx7yyx
            references public.users,
    primary key (role_id, user_id)
);

alter table public.user_role
    owner to postgres;

